name: test stack

on:
  # schedule:
  #   - cron: '0 0,6,12,18 * * *'  
    
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-app]

# concurrency:
#   group: n8n
#   cancel-in-progress: false
  
jobs:
  docker-compose:
    runs-on: ubuntu-latest
    env:
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
      R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
      R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
      R2_BUCKET: ${{ secrets.R2_BUCKET }}
      DB_PATH: ${{ secrets.DB_PATH }}
      CRAWL_DB_PATH: ${{ secrets.CRAWL_DB_PATH }}
      N8N_DB_PATH: ${{ secrets.N8N_DB_PATH }}
      TUNNEL_TOKEN: ${{ secrets.TUNNEL_TOKEN }}
      API_KEY: ${{ secrets.API_KEY }}
      TS_CLIENT_ID: ${{ secrets.TS_CLIENT_ID }}
      TS_CLIENT_SECRET: ${{ secrets.TS_CLIENT_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup age
        uses: AnimMouse/setup-age@v1
        with:
          token: ${{secrets.GH_TOKEN}}
          
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }} 

      - name: Restore secrets (certs & argo)
        run: |
          mkdir -p ~/.ssh
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDaUKIHX7q8BhqvjnnFTPl6UVjzJeqS5bXV9NlNp5+GeIgoq/tHa/S9egan9jsVF3yNOSD4OdcHfJ9RpC0Kc7WT5RDgl8DzyyvFRmiQIsJogrOCN7PAWLv0IaAZqLOdTKgfu6L8LgCur5KnFM5t0AuK28TXIa6cs97EsM5zaIJRJcOlJP3YR1f4NG2XlBWk1CDNn90pVXnvd59tOqq6rnu6h4ste9FEpczkx9jUTTKt0e77+S8Z7+Nt5rEYEbcdoZ6WeWkPAuBltN43NZBGdD0XgIwMq57A5fmWBZ6j2kJy6sXKkYXh0X+YQ56YPLwsXb5YXDzLsoPGWPJdi5yk1h1x" >> ~/.ssh/authorized_keys
          # docker create --name temp ghcr.io/${{ github.repository }}/bak:latest true
          # docker cp temp:/app/db.tar.gz.age ~/
          mkdir -p ~/db
          # age -d -i <(echo $AGE_SECRET_KEY) ~/db.tar.gz.age | tar -xz -C ~/
          
          echo "DATE_TAG=$(date +%d-%m-%Y-%H-%M)" >> $GITHUB_ENV
          ARTIFACT_RUN_ID=$(curl -s "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?per_page=1" | jq '.artifacts[0].workflow_run.id')
          echo "artifact_run_id=$ARTIFACT_RUN_ID" >> $GITHUB_ENV
      
      - name: Free disk space
        run: |
          sudo swapoff -a
          # sudo apt-get autoremove -y
          # sudo apt-get autoclean -y
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/lib/jvm /usr/share/swift /usr/local/.ghcup /usr/local/julia* /usr/local/share/chromium /opt/microsoft /opt/google /opt/az /usr/local/share/powershell
                  
      - name: Download previous DB
        uses: actions/download-artifact@v5
        with:
          name: db
          # path: /var/lib/docker/volumes/argosbx_n8n_data/_data
          path: /home/runner/db
          run-id: ${{ env.artifact_run_id }}
          github-token: ${{ secrets.GH_TOKEN }}
        continue-on-error: true


      # - name: Cache Docker images.
      #   uses: AndreKurait/docker-cache@0.6.0
      #   with:
      #     key: docker-${{ runner.os }}-${{ hashFiles('n8n.yml') }}

      - name: Run docker-compose
        run: |
          sudo chmod -R 777 /home/runner/db
          docker compose -f app.yml up -d
          # sleep 1m
          # docker exec mini-player-n8n-1 sh -c '
          # mkdir -p /home/node/.n8n/nodes &&
          # cd /home/node/.n8n/nodes &&
          # npm install n8n-nodes-sqlite3
          # '
          
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_CLIENT_SECRET }}
          # version: 1.90.9
          tags: tag:github
          hostname: manga-gh
          
      # - name: Free disk space
      #   run: |
      #     sudo swapoff -a
      #     sudo apt-get autoremove -y
      #     sudo apt-get autoclean -y
      #     sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          all_but_latest: true

      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          repository: ${{ github.repository }}
          older-than-seconds: 604800 # 7 days

      - name: Do your work
        run: |
          sleep 5.7h
          
      - name: stop n8n
        run: |
          docker compose -f app.yml stop n8n
          cd /home/runner/db/
          sqlite3 crawl.db "PRAGMA wal_checkpoint(TRUNCATE);"
          sqlite3 hachiraw.db "PRAGMA wal_checkpoint(TRUNCATE);"
          sqlite3 database.sqlite "PRAGMA wal_checkpoint(TRUNCATE);"
          
      - name: backup DB
        uses: actions/upload-artifact@v4
        with:
          name: db
          # path: /var/lib/docker/volumes/argosbx_n8n_data/_data
          path: |
            /home/runner/db/*.sqlite
            /home/runner/db/*.db
          retention-days: 90
          compression-level: 6
          continue-on-error: true
          
      - name: Prepare files
        run: |
          # mkdir ~/tmp
          # sudo cp -r /home/runner/db/*.sqlite* ~/tmp
          # sudo cp -r /home/runner/db/*.db* ~/tmp
          # sudo chown -R runner:runner ~/tmp
          find /home/runner/db -type f \( -name "*.db" -o -name "*.sqlite" -o -name "wget" \) -print0 | tar --null -czf - --files-from=- | age -r age17e5pz635kejcszp2srn87tv6s64mzdd7g2ztskfz77jhujswtg2syzqqy8 > "$GITHUB_WORKSPACE/db.tar.gz.age"

      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/bak:latest
            ghcr.io/${{ github.repository }}/bak:${{ env.DATE_TAG }}
          
      - name: Trigger next run
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"deploy-app"}'

      - name: Do your work
        run: |
          sleep 5m
